seed = 4
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-bank-marketing"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 4.502541439904779e-05
weight_decay = 0.0

[model]
arch_type = "tabrmv3"
sample_rate = 0.2922221674856657
k = 8

[model.backbone]
embed_type = "tabr"
ensemble_type = "shared-resnet"
context_shuffle = false
context_size = 192
encoder_n_blocks = 0
n_blocks = 2
d_block = 928
dropout = 0.0

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 56
d_embedding = 32
frequency_init_scale = 0.31142489587815286
lite = false
